# build stage
FROM golang:1.9.2 AS build-env

RUN go get github.com/go-redis/redis
RUN go get github.com/gorilla/mux
RUN go get github.com/gorilla/sessions

ADD . /src
RUN cd /src && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# final stage
FROM alpine
WORKDIR /app
COPY --from=build-env /src/main /app/
ADD /templates /app/templates
ENTRYPOINT ./main

EXPOSE 8080
